### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by hari-sikchi** [hari-sikchi/bsnake_lane_detection#1]
Provide a proper documentation for the CHEVP algorithms .Refer to http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.106.6644&rep=rep1&type=pdf 
for details

**Comment by dublevsky** [comment]
Hey, i want to help you, what exactly do you need in your readme regarding the code?

**Comment by seancyw** [comment]
Hi there, can I work on this?

**Comment by hari-sikchi** [comment]
Sure,follow the link and get started
